### ISSUE TITLE
X-Compile

### ISSUE THREAD

**Issue by Dastano** [darkiaspis/linux-switch-docker#1]
Hey,

thanks for this docker and quick writeup.

I currently stuck at: 

sudo docker run -it -d -v $PWD:/opt pega/linux-switch /bin/bash -c "cd /opt; ./commands.sh"
Unable to find image 'pega/linux-switch:latest' locally
docker: Error response from daemon: pull access denied for pega/linux-switch, repository does not exist or may require 'docker login'.
See 'docker run --help'.

I tried different things, like just /linux-switch etc.

**Comment by Quwel** [comment]
same issue here with it not being able to pull the docker

**Comment by darkiaspis** [comment]
Please read the docker user guide if you wanna build by your own. Otherwise, just pull the prebuild image as specified in the readme
